#!/bin/bash

# Copyright (c) Calibra. All Rights Reserved

# run this script from the project root using `./scripts/build_docs.sh`

usage() {
  echo "Usage: $0 [-b]"
  echo ""
  echo "Build Libra documentation."
  echo ""
  echo "  -b   Build static version of documentation (otherwise start server)"
  echo ""
  exit 1
}

BUILD_STATIC=false

while getopts 'hb' flag; do
  case "${flag}" in
    h)
      usage
      ;;
    b)
      BUILD_STATIC=true
      ;;
    *)
      usage
      ;;
  esac
done

# Clone libra
rm -rf doc_tmp
mkdir doc_tmp
git clone git@github.com:libra/libra.git doc_tmp/libra

# manually copy crate README files from fixed directory
###
echo "-----------------------------------"
echo "Manually Copying READMEs to docs/crates"
echo "-----------------------------------"
sed -i.old '/^# /d' doc_tmp/libra/admission_control/README.md; cp doc_tmp/libra/admission_control/README.md docs/crates/admission-control.md
sed -i.old '/^# /d' doc_tmp/libra/language/bytecode_verifier/README.md; cp doc_tmp/libra/language/bytecode_verifier/README.md docs/crates/bytecode-verifier.md
sed -i.old '/^# /d' doc_tmp/libra/consensus/README.md; cp doc_tmp/libra/consensus/README.md docs/crates/consensus.md
sed -i.old '/^# /d' doc_tmp/libra/crypto/legacy_crypto/README.md; cp doc_tmp/libra/crypto/legacy_crypto/README.md docs/crates/crypto.md
sed -i.old '/^# /d' doc_tmp/libra/execution/README.md; cp doc_tmp/libra/execution/README.md docs/crates/execution.md
sed -i.old '/^# /d' doc_tmp/libra/language/README.md; cp doc_tmp/libra/language/README.md docs/crates/move-language.md
sed -i.old '/^# /d' doc_tmp/libra/language/compiler/README.md; cp doc_tmp/libra/language/compiler/README.md docs/crates/ir-to-bytecode.md
sed -i.old '/^# /d' doc_tmp/libra/mempool/README.md; cp doc_tmp/libra/mempool/README.md docs/crates/mempool.md
sed -i.old '/^# /d' doc_tmp/libra/network/README.md; cp doc_tmp/libra/network/README.md docs/crates/network.md
sed -i.old '/^# /d' doc_tmp/libra/storage/README.md; cp doc_tmp/libra/storage/README.md docs/crates/storage.md
sed -i.old '/^# /d' doc_tmp/libra/language/vm/README.md; cp doc_tmp/libra/language/vm/README.md docs/crates/vm.md

echo "-----------------------------------"
echo "Manually Copy Coding Guidelines"
echo "-----------------------------------"
sed -i.old '/^# Libra Core coding guidelines/d' doc_tmp/libra/documentation/coding_guidelines.md
cp doc_tmp/libra/documentation/coding_guidelines.md docs/community/coding-guidelines.md

# echo "-----------------------------------"
# echo "Generating API reference via Rustdoc"
# echo "-----------------------------------"

# cargo doc --no-deps
# cd ../../website
# RUSTDOC_DIR='../libra/target/doc/'
# DOCUSAURUS_RUSTDOC_DIR='./website/build/website/rustdoc/'

# mkdir -p $DOCUSAURUS_RUSTDOC_DIR
# cp -r $RUSTDOC_DIR $DOCUSAURUS_RUSTDOC_DIR

# cd .. || exit

echo "-----------------------------------"
echo "Building Docusaurus 🦖"
echo "-----------------------------------"
cd website || exit
yarn

# run script to parse html generated by rustdoc
# echo "-----------------------------------"
# echo "Parsing Rustdoc and Protogen docs and moving to Docusaurus"
# echo "-----------------------------------"
# cd ..
# mkdir -p "website/pages/api/"

# cd website || exit

if [[ $BUILD_STATIC == true ]]; then
  echo "-----------------------------------"
  echo "Building static site"
  echo "-----------------------------------"
  yarn build
else
  echo "-----------------------------------"
  echo "Starting local server"
  echo "-----------------------------------"
  yarn start
fi
